<?php
namespace app\widgets\pjaxloader;

use app\widgets\pjaxloader\source\PjaxLoaderAssets;

class PjaxLoader extends \yii\widgets\Pjax
{

    public function run()
    {
        PjaxLoaderAssets::register(\Yii::$app->view);
        return parent::run(); // TODO: Change the autogenerated stub
    }
}