<?php
namespace app\modules\lang\widgets;


use yii\base\Widget;

class LangWidget extends Widget
{
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        $currentLang = \Yii::$app->language;
        $languageList = \Yii::$app->params['languages']['list'];
        return $this->render('lang', compact('currentLang', 'languageList'));
    }
}