<?php

namespace app\modules\page;

use yii\filters\AccessControl;

/**
 * Page module definition class
 */
class PageModule extends \yii\base\Module
{
    /**
     * @inheritdoc
     */
    public $controllerNamespace = 'app\modules\page\controllers';

    /**
     * layout админ части модуля
     * @var
     */
    public $adminLayout;

    public $adminRoles = ['@'];

    public function beforeAction($action)
    {
        if(preg_match('/admin/', $action->controller->id)) {
            $this->layout = $this->adminLayout;
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => $this->adminRoles,
                    ]
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function init()
    {
        parent::init();

        // custom initialization code goes here
    }
}
